'use client';

//
// src/components/landing/HeroSection.tsx
//
// Landing page hero per M2 Section 4.8 Kalypso output spec + RV_PLAN.md RV.5
// Landing architecture: full-viewport hero + tagline "Infrastructure for the
// AI agent economy" (exact locked string, V1 project identity lock) + demo
// preview video slot + primary CTA "Play in browser" to /play + secondary CTA
// to GitHub repo. NO embedded Phaser canvas (M2 Section 4.8 hard stop: link
// only via Next.js Link). NO 3D WebGL (M2 Section 4.8 hard stop: Tailwind +
// Framer Motion only).
//
// Client Component because Framer Motion entrance animation needs the
// browser runtime. The parent Server Component `app/page.tsx` stays server
// per RV.5 minimal-render direction and imports this Client child.
//
// W3 draft: video source is a placeholder generated by ffmpeg, W4 will
// replace with the actual vertical-slice demo recording from Thalia-v2 +
// Nyx + Linus + Erato-v2 output.
//

import Link from 'next/link';
import { motion, useReducedMotion } from 'framer-motion';

export function HeroSection() {
  const reduceMotion = useReducedMotion();

  const fadeUp = reduceMotion
    ? { initial: {}, animate: {}, transition: {} }
    : {
        initial: { opacity: 0, y: 24 },
        animate: { opacity: 1, y: 0 },
        transition: { duration: 0.6, ease: 'easeOut' as const },
      };

  const fadeUpDelay = (delaySeconds: number) =>
    reduceMotion
      ? { initial: {}, animate: {}, transition: {} }
      : {
          initial: { opacity: 0, y: 18 },
          animate: { opacity: 1, y: 0 },
          transition: {
            duration: 0.55,
            delay: delaySeconds,
            ease: 'easeOut' as const,
          },
        };

  return (
    <section
      id="hero"
      aria-label="NERIUM hero"
      className="relative flex min-h-screen w-full flex-col items-center justify-center overflow-hidden bg-background px-6 py-16 text-foreground"
    >
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(140,200,255,0.08),transparent_60%)]"
      />

      <motion.p
        {...fadeUp}
        className="mb-4 font-mono text-sm uppercase tracking-[0.3em] text-muted"
      >
        Cerebral Valley plus Anthropic hackathon, April 2026
      </motion.p>

      <motion.h1
        {...fadeUpDelay(0.1)}
        className="max-w-5xl text-center font-serif text-4xl font-semibold leading-tight tracking-tight text-foreground sm:text-5xl md:text-6xl lg:text-7xl"
      >
        Infrastructure for the AI agent economy
      </motion.h1>

      <motion.p
        {...fadeUpDelay(0.2)}
        className="mt-6 max-w-2xl text-center text-lg leading-relaxed text-muted sm:text-xl"
      >
        NERIUM is a five-pillar platform. Builder is the flagship, a gamified
        agent orchestrator you play through in a browser. Marketplace,
        Banking, Registry, and Protocol round out the stack.
      </motion.p>

      <motion.div
        {...fadeUpDelay(0.3)}
        className="mt-10 flex flex-col items-center gap-4 sm:flex-row"
      >
        <Link
          href="/play"
          prefetch={false}
          className="inline-flex items-center justify-center rounded-pill bg-primary px-8 py-3 font-semibold text-background transition-all duration-150 hover:opacity-90 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 focus:ring-offset-background motion-reduce:transition-none"
        >
          Play in browser
        </Link>
        <a
          href="https://github.com/Finerium/nerium"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center justify-center rounded-pill border border-border bg-transparent px-8 py-3 font-semibold text-foreground transition-colors duration-150 hover:border-primary hover:text-primary focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 focus:ring-offset-background motion-reduce:transition-none"
        >
          View source on GitHub
        </a>
      </motion.div>

      <motion.div
        {...fadeUpDelay(0.45)}
        className="mt-14 w-full max-w-5xl"
      >
        <div className="relative aspect-video w-full overflow-hidden rounded-lg border border-border bg-[oklch(0.16_0.03_270)] shadow-2xl">
          <video
            aria-label="NERIUM vertical slice preview"
            className="h-full w-full object-cover"
            autoPlay
            loop
            muted
            playsInline
            poster="/video/demo-preview-poster.svg"
          >
            <source src="/video/demo-preview.mp4" type="video/mp4" />
            Your browser does not support embedded video. Visit the
            <Link href="/play" className="underline">play</Link> route for the
            live prototype.
          </video>
          <div
            aria-hidden="true"
            className="pointer-events-none absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-background to-transparent"
          />
          <p className="absolute left-4 top-4 rounded-pill border border-border bg-background/70 px-3 py-1 font-mono text-xs uppercase tracking-widest text-muted">
            vertical slice preview, W4 finalize pending
          </p>
        </div>
      </motion.div>
    </section>
  );
}
